//
// packet.h
//

#define	ORB_UNKNOWN_PACKET	0
#define	ORB_RESET_PACKET	1
#define	ORB_BALL_DATA_PACKET	2
#define	ORB_BUTTON_DATA_PACKET	3
#define	ORB_ERROR_PACKET	4
#define	ORB_NULL_REGION_PACKET	5
#define	ORB_TERM_PACKET		6

#define	ORB_PACKET_BUFFER_LENGTH	60
