//
// debug.c
//

#include "orbenum.h"

#if	DBG

unsigned long OrbDebugLevel = ORB_DBG_ALL;

PCHAR
DbgSerIoctlToStr(IN ULONG ioctlCode)
{
	switch (ioctlCode) {
	case IOCTL_SERIAL_SET_BAUD_RATE:
		return "SET_BAUD_RATE";
	case IOCTL_SERIAL_SET_QUEUE_SIZE:
		return "SET_QUEUE_SIZE";
	case IOCTL_SERIAL_SET_LINE_CONTROL:
		return "SET_LINE_CONTROL";
	case IOCTL_SERIAL_SET_BREAK_ON:
		return "SET_BREAK_ON";
	case IOCTL_SERIAL_SET_BREAK_OFF:
		return "SET_BREAK_OFF";
	case IOCTL_SERIAL_IMMEDIATE_CHAR:
		return "IMMEDIATE_CHAR";
	case IOCTL_SERIAL_SET_TIMEOUTS:
		return "SET_TIMEOUTS";
	case IOCTL_SERIAL_GET_TIMEOUTS:
		return "GET_TIMEOUTS";
	case IOCTL_SERIAL_SET_DTR:
		return "SET_DTR";
	case IOCTL_SERIAL_CLR_DTR:
		return "CLR_DTR";
	case IOCTL_SERIAL_RESET_DEVICE:
		return "RESET_DEVICE";
	case IOCTL_SERIAL_SET_RTS:
		return "SET_RTS";
	case IOCTL_SERIAL_CLR_RTS:
		return "CLR_RTS";
	case IOCTL_SERIAL_SET_XOFF:
		return "SET_XOFF";
	case IOCTL_SERIAL_SET_XON:
		return "SET_XON";
	case IOCTL_SERIAL_GET_WAIT_MASK:
		return "GET_WAIT_MASK";
	case IOCTL_SERIAL_SET_WAIT_MASK:
		return "SET_WAIT_MASK";
	case IOCTL_SERIAL_WAIT_ON_MASK:
		return "WAIT_ON_MASK";
	case IOCTL_SERIAL_PURGE:
		return "PURGE";
	case IOCTL_SERIAL_GET_BAUD_RATE:
		return "GET_BAUD_RATE";
	case IOCTL_SERIAL_GET_LINE_CONTROL:
		return "GET_LINE_CONTROL";
	case IOCTL_SERIAL_GET_CHARS:
		return "GET_CHARS";
	case IOCTL_SERIAL_SET_CHARS:
		return "SET_CHARS";
	case IOCTL_SERIAL_GET_HANDFLOW:
		return "GET_HANDFLOW";
	case IOCTL_SERIAL_SET_HANDFLOW:
		return "SET_HANDFLOW";
	case IOCTL_SERIAL_GET_MODEMSTATUS:
		return "GET_MODEMSTATUS";
	case IOCTL_SERIAL_GET_COMMSTATUS:
		return "GET_COMMSTATUS";
	case IOCTL_SERIAL_XOFF_COUNTER:
		return "XOFF_COUNTER";
	case IOCTL_SERIAL_GET_PROPERTIES:
		return "GET_PROPERTIES";
	case IOCTL_SERIAL_GET_DTRRTS:
		return "GET_DTRRTS";
	case IOCTL_SERIAL_LSRMST_INSERT:
		return "LSRMST_INSERT";
	case IOCTL_SERIAL_CONFIG_SIZE:
		return "CONFIG_SIZE";
	case IOCTL_SERIAL_GET_COMMCONFIG:
		return "GET_COMMCONFIG";
	case IOCTL_SERIAL_SET_COMMCONFIG:
		return "SET_COMMCONFIG";
	case IOCTL_SERIAL_GET_STATS:
		return "GET_STATS";
	case IOCTL_SERIAL_CLEAR_STATS:
		return "CLEAR_STATS";
	case IOCTL_SERIAL_GET_MODEM_CONTROL:
		return "GET_MODEM_CONTROL";
	case IOCTL_SERIAL_SET_MODEM_CONTROL:
		return "SET_MODEM_CONTROL";
	case IOCTL_SERIAL_SET_FIFO_CONTROL:
		return "SET_FIFO_CONTROL";
	default:
		return "unknown ioctl?";
	}
}

#endif
